#!/bin/bash
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100_Shear600000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500_Shear600000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma1000_Shear600000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma5000_Shear600000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma10000_Shear600000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma50000_Shear600000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma100000_Shear600000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear10000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear50000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear100000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear200000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear300000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear400000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear500000
sbatch run_omp.sh
cd /data0/home/cshang/cases/BTS_big_particle/OneHundredBTSTests/Generated_BTS_cases/BTS_Sigma500000_Shear600000
sbatch run_omp.sh
